using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


using OMS.SharedKernel.Common;

namespace OMS.SharedKernel.DTO;


public class LiveOrderDTO
{
    private DateTime _orderTime;

    public int LiveOrderID { get; set; }    
    // PlatformOrderID generate by platform of record
    public int PlatformOrderID { get; set; }

    // In the case of NinjaTrader as the execution platformn - this would be the filled order ID returned on execution
    public int ExecutedOrderID { get; set; }
    public int UserID { get; set; }
    public int GroupID { get; set; }
    public double Leverage { get; set; }
    public int Opposite { get; set; }

    // Token for successful trader authentication
    public int AuthToken { get; set; }

    // ID generated by the order manager
    public int OrderManagerID { get; set; }

    // Related orders are available to handle split orders  ex- your 5 long and you sell 3 
    public int RelatedOrderID { get; set; }
    public DateTime OrderTime
    {
        get => _orderTime;
        set => _orderTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    }
    public string Instrument { get; set; } = PlatformConstants.INVALID_SYMBOL;
    public double OrderPX { get; set; }

    // Market, Limit, Stop
    public OrderType OrderType { get; set; }

    //Buy Sell
    public OrderAction OrderAction { get; set; }
    public int Quantity { get; set; }

    public double MAE { get; set; }
    public double MFE { get; set; }

    public string ModelFeatureData { get; set; }

}