using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using OMS.SharedKernel.Common;

namespace OMS.SharedKernel.DTO;


public class NewOrderDTO
{
    private DateTime _orderTime;

    [JsonPropertyName("newOrderID")]
    [Key]
    public int NewOrderID { get; set; }

    // PlatformOrderID generated by the platform of record
    // This property represents the ID generated by the platform of record
    // In the case of NinjaTrader as the execution platform, this would be the filled order ID returned on execution
    [JsonPropertyName("platformOrderID")]  
    public int PlatformOrderID { get; set; }
    
    [JsonPropertyName("userName")]
    public string UserName { get; set; }
    
    [JsonPropertyName("userID")]
    public int UserID { get; set; }
    
    [JsonPropertyName("groupID")]
    public int GroupID { get; set; }

    // Token for successful trader authentication
    [JsonPropertyName("authToken")]
    public int AuthToken { get; set; }

    [JsonPropertyName("instrument")]
    public string Instrument { get; set; }

    [JsonPropertyName("orderPX")]
    public double OrderPX { get; set; }

    [JsonPropertyName("orderType")]
    public OrderType OrderType { get; set; }

    [JsonPropertyName("orderAction")]
    public OrderAction OrderAction { get; set; }

    [JsonPropertyName("quantity")]
    public int Quantity { get; set; }

    [JsonPropertyName("orderTime")]
     public DateTime OrderTime
    {
        get => _orderTime;
        set => _orderTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    }

    // used by the strategy to connect original order from trader to algo order
    public int RelatedOrderID { get; set; }

    public string ModelFeatureData { get; set; }
}