select  "StorerID"
,"UserID"
,"GroupID"
,"Instrument"
,"Quantity"
,"OpenPlatformOrderID"
,"OpenExecutionID"
,"OpenRelatedOrderID"
,"OpenOrderTime"
,"OpenOrderPX"
,"OpenOrderAction"
,"CloseExecutionID"
,"ClosePlatformOrderID"
,"CloseRelatedOrderID"
,"CloseOrderTime"
,"CloseOrderPX"
,"CloseOrderType"
,"CloseOrderAction"
,"PNL"
,"MAE"
,"MFE"
,"NetChange"
,"Version"
from public."ClosedTrades"
LIMIT 1000