select  "StorerID"
,"UserID"
,"GroupID"
,"OpenPlatformOrderID"
,"OpenRelatedOrderID"
,"ClosePlatformOrderID"
,"CloseRelatedOrderID"
,"OpenOrderTime"
,"OpenOrderPX"
,"OpenOrderType"
,"OpenOrderAction"
,"CloseOrderTime"
,"CloseOrderPX"
,"CloseOrderType"
,"CloseOrderAction"
,"PNL"
,"Instrument"
,"Quantity"

from public."ClosedTrades"