select  "StorerID"
,"UserID"
,"GroupID"
,"Instrument"
,"Quantity"
,"OpenPlatformOrderID"
,"OpenOrderMangerID"
,"OpenExecutionID"
,"OpenRelatedOrderID"
,"OpenOrderTime"
,"OpenOrderPX"
,"OpenOrderType"
,"OpenOrderAction"
,"ClosePlatformOrderID"
,"ClosedOrderMangerID"
,"CloseExecutionID"
,"CloseRelatedOrderID"
,"CloseOrderTime"
,"CloseOrderPX"
,"CloseOrderType"
,"CloseOrderAction"
,"PNL"
from public."ClosedTrades"