<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OMS.Application\OMS.Application.csproj" />
    <ProjectReference Include="..\OMS.Infrastructure\OMS.Infrastructure.csproj" />
    <ProjectReference Include="..\OMS.SharedKernel\OMS.SharedKernel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
