-- Table: public.FeatureData

-- DROP TABLE IF EXISTS public."FeatureData";

CREATE TABLE IF NOT EXISTS public."FeatureData"
(
    "FeatureSetID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FeatureSetData" text COLLATE pg_catalog."default",
    "FeatureSetName" text COLLATE pg_catalog."default",
    "FeatureNameData" text COLLATE pg_catalog."default",
    "TimeTicks" bigint NOT NULL,
    "Instrument" text COLLATE pg_catalog."default",
    "Open" double precision NOT NULL,
    "High" double precision NOT NULL,
    "Low" double precision NOT NULL,
    "Close" double precision NOT NULL,
    CONSTRAINT "PK_FeatureData" PRIMARY KEY ("FeatureSetID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."FeatureData"
    OWNER to dean;