// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OMS.Infrastructure.Data;

#nullable disable

namespace OMS.Infrastructure.Migrations
{
    [DbContext(typeof(OrderManagementDbContext))]
    partial class OrderManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OMS.Core.Models.ActivityLog", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActivityID"));

                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionGuid")
                        .HasColumnType("text");

                    b.Property<int>("SessionID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ActivityID");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("OMS.Core.Models.ClosedTrade", b =>
                {
                    b.Property<int>("StorerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StorerID"));

                    b.Property<int>("CloseAuthToken")
                        .HasColumnType("integer");

                    b.Property<int>("CloseExecutionID")
                        .HasColumnType("integer");

                    b.Property<int>("CloseOrderAction")
                        .HasColumnType("integer");

                    b.Property<double>("CloseOrderPX")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CloseOrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CloseOrderType")
                        .HasColumnType("integer");

                    b.Property<int>("ClosePlatformOrderID")
                        .HasColumnType("integer");

                    b.Property<int>("CloseRelatedOrderID")
                        .HasColumnType("integer");

                    b.Property<int>("ClosedOrderMangerID")
                        .HasColumnType("integer");

                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.Property<string>("Instrument")
                        .HasColumnType("text");

                    b.Property<double>("Leverage")
                        .HasColumnType("double precision");

                    b.Property<double>("MAE")
                        .HasColumnType("double precision");

                    b.Property<double>("MFE")
                        .HasColumnType("double precision");

                    b.Property<double>("NetChange")
                        .HasColumnType("double precision");

                    b.Property<int>("OpenAuthToken")
                        .HasColumnType("integer");

                    b.Property<int>("OpenExecutionID")
                        .HasColumnType("integer");

                    b.Property<int>("OpenOrderAction")
                        .HasColumnType("integer");

                    b.Property<int>("OpenOrderMangerID")
                        .HasColumnType("integer");

                    b.Property<double>("OpenOrderPX")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("OpenOrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpenOrderType")
                        .HasColumnType("integer");

                    b.Property<int>("OpenPlatformOrderID")
                        .HasColumnType("integer");

                    b.Property<int>("OpenRelatedOrderID")
                        .HasColumnType("integer");

                    b.Property<bool>("OppositeTrader")
                        .HasColumnType("boolean");

                    b.Property<double>("PNL")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("StorerID");

                    b.ToTable("ClosedTrades");
                });

            modelBuilder.Entity("OMS.Core.Models.LiveOrder", b =>
                {
                    b.Property<int>("LiveOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LiveOrderID"));

                    b.Property<int>("AuthToken")
                        .HasColumnType("integer");

                    b.Property<int>("ExecutedOrderID")
                        .HasColumnType("integer");

                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.Property<string>("Instrument")
                        .HasColumnType("text");

                    b.Property<double>("Leverage")
                        .HasColumnType("double precision");

                    b.Property<double>("MAE")
                        .HasColumnType("double precision");

                    b.Property<double>("MFE")
                        .HasColumnType("double precision");

                    b.Property<int>("Opposite")
                        .HasColumnType("integer");

                    b.Property<int>("OrderAction")
                        .HasColumnType("integer");

                    b.Property<int>("OrderManagerID")
                        .HasColumnType("integer");

                    b.Property<double>("OrderPX")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformOrderID")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RelatedOrderID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("LiveOrderID");

                    b.ToTable("LiveOrder");
                });

            modelBuilder.Entity("OMS.Core.Models.OrderFlow", b =>
                {
                    b.Property<int>("OrderFlowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderFlowId"));

                    b.Property<int>("AuthToken")
                        .HasColumnType("integer");

                    b.Property<int>("ExecutedOrderID")
                        .HasColumnType("integer");

                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.Property<string>("Instrument")
                        .HasColumnType("text");

                    b.Property<double>("Leverage")
                        .HasColumnType("double precision");

                    b.Property<int>("Opposite")
                        .HasColumnType("integer");

                    b.Property<int>("OrderAction")
                        .HasColumnType("integer");

                    b.Property<int>("OrderManagerID")
                        .HasColumnType("integer");

                    b.Property<double>("OrderPX")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformOrderID")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RelatedOrderID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("OrderFlowId");

                    b.ToTable("OrderFlow");
                });

            modelBuilder.Entity("OMS.Core.Models.ScoreCard", b =>
                {
                    b.Property<int>("ScoreCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScoreCardID"));

                    b.Property<double>("AveLoss")
                        .HasColumnType("double precision");

                    b.Property<double>("AveLossDuration")
                        .HasColumnType("double precision");

                    b.Property<double>("AveTradeDuration")
                        .HasColumnType("double precision");

                    b.Property<double>("AveWin")
                        .HasColumnType("double precision");

                    b.Property<double>("AveWinDuration")
                        .HasColumnType("double precision");

                    b.Property<double>("GrossLoss")
                        .HasColumnType("double precision");

                    b.Property<double>("GrossProfit")
                        .HasColumnType("double precision");

                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.Property<double>("LargestLoser")
                        .HasColumnType("double precision");

                    b.Property<int>("LargestLosingStreak")
                        .HasColumnType("integer");

                    b.Property<double>("LargestWinner")
                        .HasColumnType("double precision");

                    b.Property<int>("LargestWinningStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Longs")
                        .HasColumnType("integer");

                    b.Property<int>("Losers")
                        .HasColumnType("integer");

                    b.Property<double>("NetProfitLong")
                        .HasColumnType("double precision");

                    b.Property<double>("NetProfitShort")
                        .HasColumnType("double precision");

                    b.Property<double>("PNL_Last13")
                        .HasColumnType("double precision");

                    b.Property<double>("PNL_Last21")
                        .HasColumnType("double precision");

                    b.Property<double>("PNL_Last3")
                        .HasColumnType("double precision");

                    b.Property<double>("PNL_Last34")
                        .HasColumnType("double precision");

                    b.Property<double>("PNL_Last5")
                        .HasColumnType("double precision");

                    b.Property<double>("PNL_Last8")
                        .HasColumnType("double precision");

                    b.Property<double>("SharpRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("Shorts")
                        .HasColumnType("integer");

                    b.Property<double>("SortinoRatio")
                        .HasColumnType("double precision");

                    b.Property<double>("StdDevAllTrades")
                        .HasColumnType("double precision");

                    b.Property<double>("StdDevLossTrades")
                        .HasColumnType("double precision");

                    b.Property<double>("StdDevWinTrades")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalNetProfit")
                        .HasColumnType("double precision");

                    b.Property<string>("TradeXML")
                        .HasColumnType("text");

                    b.Property<int>("Trades")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<double>("WinLossRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("Winners")
                        .HasColumnType("integer");

                    b.HasKey("ScoreCardID");

                    b.ToTable("ScoreCard");

                    b.HasData(
                        new
                        {
                            ScoreCardID = 1,
                            AveLoss = 0.0,
                            AveLossDuration = 0.0,
                            AveTradeDuration = 0.0,
                            AveWin = 0.0,
                            AveWinDuration = 0.0,
                            GrossLoss = 0.0,
                            GrossProfit = 0.0,
                            GroupID = 0,
                            LargestLoser = 0.0,
                            LargestLosingStreak = 0,
                            LargestWinner = 0.0,
                            LargestWinningStreak = 0,
                            LastUpdate = new DateTime(2024, 3, 6, 20, 26, 58, 352, DateTimeKind.Utc).AddTicks(7130),
                            Longs = 0,
                            Losers = 7,
                            NetProfitLong = 0.0,
                            NetProfitShort = 0.0,
                            PNL_Last13 = 0.0,
                            PNL_Last21 = 0.0,
                            PNL_Last3 = 0.0,
                            PNL_Last34 = 0.0,
                            PNL_Last5 = 0.0,
                            PNL_Last8 = 0.0,
                            SharpRatio = 0.0,
                            Shorts = 0,
                            SortinoRatio = 0.0,
                            StdDevAllTrades = 0.0,
                            StdDevLossTrades = 0.0,
                            StdDevWinTrades = 0.0,
                            TotalNetProfit = 0.0,
                            TradeXML = "",
                            Trades = 10,
                            UserID = 999999,
                            WinLossRatio = 0.29999999999999999,
                            Winners = 3
                        },
                        new
                        {
                            ScoreCardID = 2,
                            AveLoss = 0.0,
                            AveLossDuration = 0.0,
                            AveTradeDuration = 0.0,
                            AveWin = 0.0,
                            AveWinDuration = 0.0,
                            GrossLoss = 0.0,
                            GrossProfit = 0.0,
                            GroupID = 0,
                            LargestLoser = 0.0,
                            LargestLosingStreak = 0,
                            LargestWinner = 0.0,
                            LargestWinningStreak = 0,
                            LastUpdate = new DateTime(2024, 3, 6, 20, 26, 58, 352, DateTimeKind.Utc).AddTicks(7150),
                            Longs = 0,
                            Losers = 0,
                            NetProfitLong = 0.0,
                            NetProfitShort = 0.0,
                            PNL_Last13 = 0.0,
                            PNL_Last21 = 0.0,
                            PNL_Last3 = 0.0,
                            PNL_Last34 = 0.0,
                            PNL_Last5 = 0.0,
                            PNL_Last8 = 0.0,
                            SharpRatio = 0.0,
                            Shorts = 0,
                            SortinoRatio = 0.0,
                            StdDevAllTrades = 0.0,
                            StdDevLossTrades = 0.0,
                            StdDevWinTrades = 0.0,
                            TotalNetProfit = 0.0,
                            TradeXML = "",
                            Trades = 10,
                            UserID = 999998,
                            WinLossRatio = 0.69999999999999996,
                            Winners = 0
                        });
                });

            modelBuilder.Entity("OMS.Core.Models.UserProfile", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("Enabled")
                        .HasColumnType("integer");

                    b.Property<int>("EnabledLive")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.Property<int>("GroupRank")
                        .HasColumnType("integer");

                    b.Property<int>("IsOpposite")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<double>("Leverage")
                        .HasColumnType("double precision");

                    b.Property<int>("TraderRole")
                        .HasColumnType("integer");

                    b.Property<string>("UserPwd")
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            UserID = 999999,
                            DateRegistered = new DateTime(2024, 3, 6, 12, 26, 58, 352, DateTimeKind.Utc).AddTicks(7050),
                            DisplayName = "User1",
                            Email = "admin",
                            Enabled = 1,
                            EnabledLive = 0,
                            FirstName = "User",
                            GroupID = 0,
                            GroupRank = 0,
                            IsOpposite = 0,
                            LastName = "One",
                            Leverage = 0.0,
                            TraderRole = 0,
                            UserPwd = "abc"
                        },
                        new
                        {
                            UserID = 999998,
                            DateRegistered = new DateTime(2024, 3, 6, 12, 26, 58, 352, DateTimeKind.Utc).AddTicks(7110),
                            DisplayName = "User2",
                            Email = "admin",
                            Enabled = 1,
                            EnabledLive = 0,
                            FirstName = "User",
                            GroupID = 0,
                            GroupRank = 0,
                            IsOpposite = 0,
                            LastName = "One",
                            Leverage = 0.0,
                            TraderRole = 0,
                            UserPwd = "abc"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
