using System.ComponentModel.DataAnnotations;
using OMS.Core.Common;


namespace OMS.Core.DTO;

[GenerateSerializer]
[Alias("NewOrderDTO")]
public class NewOrderDTO
{
    [Id(12)]
    private DateTime _orderTime;

    [Key]
    [Id(10)]
    /// <summary>
    /// Gets or sets the new order ID.
    /// </summary>
    public int NewOrderID { get; set; }

    // PlatformOrderID generated by the platform of record
    // This property represents the ID generated by the platform of record
    // In the case of NinjaTrader as the execution platform, this would be the filled order ID returned on execution
    [Id(11)]
    public int PlatformOrderID { get; set; }

    
    [Id(1)]
    public string UserName { get; set; }
    
    [Id(2)]
    public int UserID { get; set; }
    
    [Id(3)]
    public int GroupID { get; set; }

    // Token for successful trader authentication
    [Id(4)]
    public int AuthToken { get; set; }
    
    [Id(5)]
    public required string Instrument { get; set; }
    
    [Id(6)]
    public double OrderPX { get; set; }

    // Market, Limit, Stop
    [Id(7)]
    public OrderType OrderType { get; set; }

    // Buy, Sell
    [Id(8)]
    public OrderAction OrderAction { get; set; }
    
    [Id(9)]
    public int Quantity { get; set; }

     public DateTime OrderTime
    {
        get => _orderTime;
        set => _orderTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    }

    [Id(13)]
    // used by the strategy to connect original order from trader to algo order
    public int RelatedOrderID { get; set; }
    
}